version: "3"
services:
  broker:
    container_name: mqtt-broker
    image: eclipse-mosquitto
    volumes:
      - ./data/mosquitto/:/mosquitto/data
      - ./data/mosquitto/:/mosquitto/logs
      - "./mosquitto/conf:/mosquitto/config"
    ports:
      - "1883:1883"

  nodered:
    container_name: nodered
    depends_on:
      - broker
    image: nodered/node-red:latest
    volumes:
      - "./data/nodered:/data"
    user: "0"
    ports:
       - "1880:1880"

#networks:
#    default:
#      external: true       
#      name: flask_server_backend


