version: "3"
services:
  broker:
    container_name: mqtt-broker
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/logs:/mosquitto/logs
      - ./mosquitto/conf:/mosquitto/config
    ports:
      - "1883:1883"
      - "8883:8883"      

  nodered:
    container_name: nodered
    depends_on:
      - broker
    image: nodered/node-red:latest
    volumes:
      - "./node-red/data:/data"
    user: "1000"
    ports:
       - "1880:1880"

#networks:
#    default:
#      external: true       
#      name: flask_server_backend


