version: "3.6"

services:
    influxdb:
        container_name: influxdb
        image: influxdb
        restart: unless-stopped
        ports:
            - "8086:8086"    
        env_file:
            - "influxdb.env"                  
        volumes:
            - ./data/influxdb:/var/lib/influxdb2
            - ./data/influxdb:/etc/influxdb2            
networks:
    default:
      external: true       
      name: flask_server_backend

